/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    'Animcontainer.component': typeof import('./src/components/animcontainer/animcontainer.component.vue')['default']
    'Fadecontainer.component': typeof import('./src/components/fadecontainer/fadecontainer.component.vue')['default']
    'Filterblur.component': typeof import('./src/components/filterblur/filterblur.component.vue')['default']
    'Input.component': typeof import('./src/components/input/input.component.vue')['default']
    IosCard: typeof import('./src/components/ui/IosCard.vue')['default']
    IosCheckbox: typeof import('./src/components/ui/IosCheckbox.vue')['default']
    IosGroupSection: typeof import('./src/components/ui/IosGroupSection.vue')['default']
    IosListItem: typeof import('./src/components/ui/IosListItem.vue')['default']
    IosProgressBar: typeof import('./src/components/ui/IosProgressBar.vue')['default']
    IosSearchField: typeof import('./src/components/ui/IosSearchField.vue')['default']
    IosSegmentedControl: typeof import('./src/components/ui/IosSegmentedControl.vue')['default']
    IosStepper: typeof import('./src/components/ui/IosStepper.vue')['default']
    IosTag: typeof import('./src/components/ui/IosTag.vue')['default']
    'KeyAnimation.component': typeof import('./src/components/keyAnimation/keyAnimation.component.vue')['default']
    LiquidGlass: typeof import('./src/components/ui/LiquidGlass.vue')['default']
    'Notification.component': typeof import('./src/components/notification/notification.component.vue')['default']
    OneInput: typeof import('./src/components/input/oneInput.vue')['default']
    'Popups.container.component': typeof import('./src/components/popuscontainer/popups.container.component.vue')['default']
    'Sortlist.component': typeof import('./src/components/sortlist/sortlist.component.vue')['default']
    UAlert: typeof import('@nuxt/ui/dist/runtime/components/Alert.vue')['default']
    UAvatar: typeof import('@nuxt/ui/dist/runtime/components/Avatar.vue')['default']
    UBadge: typeof import('@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UCheckbox: typeof import('@nuxt/ui/dist/runtime/components/Checkbox.vue')['default']
    UiAlert: typeof import('./src/components/ui/UiAlert.vue')['default']
    UiAvatar: typeof import('./src/components/ui/UiAvatar.vue')['default']
    UiBadge: typeof import('./src/components/ui/UiBadge.vue')['default']
    UiButton: typeof import('./src/components/ui/UiButton.vue')['default']
    UiCard: typeof import('./src/components/ui/UiCard.vue')['default']
    UiCheckbox: typeof import('./src/components/ui/UiCheckbox.vue')['default']
    'Uifilter.component': typeof import('./src/components/uifilter/uifilter.component.vue')['default']
    UiInput: typeof import('./src/components/ui/UiInput.vue')['default']
    UiModal: typeof import('./src/components/ui/UiModal.vue')['default']
    UInput: typeof import('@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UiSelect: typeof import('./src/components/ui/UiSelect.vue')['default']
    UiSeparator: typeof import('./src/components/ui/UiSeparator.vue')['default']
    UiTabs: typeof import('./src/components/ui/UiTabs.vue')['default']
    UiTextarea: typeof import('./src/components/ui/UiTextarea.vue')['default']
    UiToggle: typeof import('./src/components/ui/UiToggle.vue')['default']
    UiTooltip: typeof import('./src/components/ui/UiTooltip.vue')['default']
    UModal: typeof import('@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    USelect: typeof import('@nuxt/ui/dist/runtime/components/Select.vue')['default']
    USeparator: typeof import('@nuxt/ui/dist/runtime/components/Separator.vue')['default']
    USwitch: typeof import('@nuxt/ui/dist/runtime/components/Switch.vue')['default']
    UTabs: typeof import('@nuxt/ui/dist/runtime/components/Tabs.vue')['default']
    UTextarea: typeof import('@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
    UTooltip: typeof import('@nuxt/ui/dist/runtime/components/Tooltip.vue')['default']
    'Viewcontainer.component': typeof import('./src/components/viewcontainer/viewcontainer.component.vue')['default']
  }
}
