export declare enum FractionsNamesEnum {
// --     gangs
	'THE_FAMILIES' = THE_FAMILIES,

	'THE_BALLAS_GANG' = THE_BALLAS_GANG,
	'LOS_SANTOS_VAGOS' = LOS_SANTOS_VAGOS,
	'MARABUNTA_GRANDE' = MARABUNTA_GRANDE,
	'BLOOD_STREET' = BLOOD_STREET,

// --     governments
	'GOVERNMENT' = GOVERNMENT,
	'POLICE_DEPARTMENT' = POLICE_DEPARTMENT,
	'HOSPITAL' = HOSPITAL,
	'FIB' = FIB,
	'ARMY' = ARMY,
	'SHERIFF' = SHERIFF,

	// --     mafias
	'LA_COSA_NOSTRA' = LA_COSA_NOSTRA,
	'ALBANIAN_MAFIA' = ALBANIAN_MAFIA,
	'YAKUZA' = YAKUZA,
	'MEXICAN_CARTEL' = MEXICAN_CARTEL,

	// --     other
	'NEWS' = NEWS,
	'THE_LOST' = THE_LOST,
	'MERRYWEATHER_SECURITY' = MERRYWEATHER_SECURITY,
}

export type FractionsNameTypes = FractionsNamesEnum;
