
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.8.0
 * Query Engine version: 3c6e192761c0362d496ed980de936e2f3cebcd3a
 */
Prisma.prismaVersion = {
  client: "7.8.0",
  engine: "3c6e192761c0362d496ed980de936e2f3cebcd3a"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.AccountsScalarFieldEnum = {
  login: 'login',
  email: 'email',
  password: 'password',
  hwid: 'hwid',
  ip: 'ip',
  social_club: 'social_club',
  donut_currency: 'donut_currency',
  vip_lvl: 'vip_lvl',
  vip_date: 'vip_date',
  promo_codes: 'promo_codes',
  bonus_codes: 'bonus_codes',
  character1: 'character1',
  character2: 'character2',
  character3: 'character3',
  characters: 'characters',
  present: 'present',
  ref_present: 'ref_present',
  case: 'case',
  referral_id: 'referral_id',
  is_subscribed: 'is_subscribed',
  subscribed_end_time: 'subscribed_end_time',
  subscribe_time: 'subscribe_time',
  collection_gifts: 'collection_gifts',
  received_award: 'received_award',
  received_award_week: 'received_award_week',
  received_award_donate: 'received_award_donate',
  Unique: 'Unique',
  last_select_character_uuid: 'last_select_character_uuid',
  exit_date: 'exit_date',
  ga: 'ga'
};

exports.Prisma.AdminsScalarFieldEnum = {
  uuid: 'uuid',
  admin_lvl: 'admin_lvl',
  admin_log: 'admin_log',
  error_log: 'error_log',
  win_log: 'win_log',
  agm: 'agm',
  kl: 'kl',
  hide_nickname: 'hide_nickname',
  hide_me: 'hide_me',
  red_name: 'red_name',
  esp: 'esp',
  is_invisible: 'is_invisible'
};

exports.Prisma.AdvertisesScalarFieldEnum = {
  advertises_id: 'advertises_id',
  author_uuid: 'author_uuid',
  author_sim: 'author_sim',
  ad: 'ad',
  link: 'link',
  editor_uuid: 'editor_uuid',
  edited_ad: 'edited_ad',
  opened_at: 'opened_at',
  closed_at: 'closed_at',
  ad_status: 'ad_status',
  ad_type: 'ad_type',
  is_premium: 'is_premium'
};

exports.Prisma.Alco_clubsScalarFieldEnum = {
  alco_club_id: 'alco_club_id',
  alco1: 'alco1',
  alco2: 'alco2',
  alco3: 'alco3',
  price_mod: 'price_mod',
  mats: 'mats'
};

exports.Prisma.BannedScalarFieldEnum = {
  uuid: 'uuid',
  name: 'name',
  account: 'account',
  time: 'time',
  until: 'until',
  is_hard_ban: 'is_hard_ban',
  ip: 'ip',
  social_club: 'social_club',
  hwid: 'hwid',
  reason: 'reason',
  by_admin: 'by_admin',
  rgsc_email_hash: 'rgsc_email_hash'
};

exports.Prisma.BattlepassScalarFieldEnum = {
  uuid: 'uuid',
  seasonid: 'seasonid',
  tasksday: 'tasksday',
  tasksweek: 'tasksweek',
  lvl: 'lvl',
  exp: 'exp',
  ispremium: 'ispremium',
  tookreward: 'tookreward',
  tookrewardpremium: 'tookrewardpremium',
  time: 'time'
};

exports.Prisma.Business_historyScalarFieldEnum = {
  business_id: 'business_id',
  date: 'date',
  uuid: 'uuid',
  item: 'item',
  price: 'price'
};

exports.Prisma.BusinessesScalarFieldEnum = {
  business_id: 'business_id',
  owner: 'owner',
  name: 'name',
  description: 'description',
  sell_price: 'sell_price',
  type: 'type',
  products: 'products',
  enter_point: 'enter_point',
  unload_point: 'unload_point',
  money: 'money',
  mafia: 'mafia',
  orders: 'orders',
  tax: 'tax'
};

exports.Prisma.Character_animation_bindScalarFieldEnum = {
  uuid: 'uuid',
  bind1: 'bind1',
  bind2: 'bind2',
  bind3: 'bind3',
  bind4: 'bind4',
  bind5: 'bind5',
  bind6: 'bind6',
  bind7: 'bind7',
  bind8: 'bind8',
  bind9: 'bind9',
  bind10: 'bind10'
};

exports.Prisma.Character_bind_cfgScalarFieldEnum = {
  uuid: 'uuid',
  bindsetting: 'bindsetting',
  chatsetting: 'chatsetting',
  animfavorites: 'animfavorites',
  adminoption: 'adminoption'
};

exports.Prisma.CharactersScalarFieldEnum = {
  uuid: 'uuid',
  is_deleted: 'is_deleted',
  deleted_date: 'deleted_date',
  firstname: 'firstname',
  lastname: 'lastname',
  gender: 'gender',
  health: 'health',
  armor: 'armor',
  lvl: 'lvl',
  exp: 'exp',
  money: 'money',
  bank: 'bank',
  work: 'work',
  fraction: 'fraction',
  fraction_lvl: 'fraction_lvl',
  drug_addicted: 'drug_addicted',
  arrest: 'arrest',
  demorgan: 'demorgan',
  wanted: 'wanted',
  biz: 'biz',
  licenses: 'licenses',
  unwarn: 'unwarn',
  unmute: 'unmute',
  warns: 'warns',
  on_duty: 'on_duty',
  last_hour: 'last_hour',
  hotel: 'hotel',
  hotel_left: 'hotel_left',
  contacts: 'contacts',
  achiev: 'achiev',
  sim_card: 'sim_card',
  petname: 'petname',
  pos: 'pos',
  create_date: 'create_date',
  demorgan_info: 'demorgan_info',
  warn_info: 'warn_info',
  time: 'time',
  deaths: 'deaths',
  kills: 'kills',
  earned_money: 'earned_money',
  eat_times: 'eat_times',
  revived: 'revived',
  hands_shaken: 'hands_shaken',
  refcode: 'refcode',
  wedding_uuid: 'wedding_uuid',
  weddingname: 'weddingname',
  missiontask: 'missiontask',
  isbannedmp: 'isbannedmp',
  banmpreason: 'banmpreason',
  isbannedcrime: 'isbannedcrime',
  bancrimereason: 'bancrimereason',
  selectedquest: 'selectedquest',
  isforbesshow: 'isforbesshow',
  fractiontasksdata: 'fractiontasksdata',
  islucky: 'islucky'
};

exports.Prisma.Characters_fractionsScalarFieldEnum = {
  uuid: 'uuid',
  fraction: 'fraction',
  fractions_rank: 'fractions_rank'
};

exports.Prisma.CompensationScalarFieldEnum = {
  auto_id: 'auto_id',
  login: 'login',
  uuid: 'uuid',
  title: 'title',
  text: 'text',
  money: 'money',
  donate: 'donate',
  itemid: 'itemid',
  data: 'data',
  toggled: 'toggled'
};

exports.Prisma.CustomizationScalarFieldEnum = {
  uuid: 'uuid',
  gender: 'gender',
  parents: 'parents',
  features: 'features',
  appearance: 'appearance',
  hair: 'hair',
  tattoos: 'tattoos',
  eyec: 'eyec',
  is_created: 'is_created'
};

exports.Prisma.Doors_controlScalarFieldEnum = {
  id: 'id',
  is_closed: 'is_closed',
  is_hard_locked: 'is_hard_locked'
};

exports.Prisma.Economy_bus_pricesScalarFieldEnum = {
  economy_bus_prices_id: 'economy_bus_prices_id',
  price: 'price'
};

exports.Prisma.Economy_license_pricesScalarFieldEnum = {
  license_type: 'license_type',
  price: 'price'
};

exports.Prisma.Fraction_clothing_setsScalarFieldEnum = {
  id: 'id',
  fraction_name: 'fraction_name',
  rank: 'rank',
  gender: 'gender',
  name: 'name',
  clothing_index: 'clothing_index'
};

exports.Prisma.Job_skillsScalarFieldEnum = {
  uuid: 'uuid',
  electrician_work: 'electrician_work',
  postman_work: 'postman_work',
  taxi_work: 'taxi_work',
  bus_driver_work: 'bus_driver_work',
  lawn_mover_work: 'lawn_mover_work',
  longhaul_truck_driver_work: 'longhaul_truck_driver_work',
  collection_agent_work: 'collection_agent_work',
  auto_mechanic_work: 'auto_mechanic_work'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};
exports.ad_status = exports.$Enums.ad_status = {
  OPENED: 'OPENED',
  CLOSED: 'CLOSED',
  REJECTED: 'REJECTED'
};

exports.ad_type = exports.$Enums.ad_type = {
  NEWS: 'NEWS',
  ADVERTISEMENT: 'ADVERTISEMENT',
  BONUS: 'BONUS',
  GREETING: 'GREETING',
  WARNING: 'WARNING',
  OTHER: 'OTHER'
};

exports.character_gender = exports.$Enums.character_gender = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
  UNKNOWN: 'UNKNOWN'
};

exports.fractions_type = exports.$Enums.fractions_type = {
  THE_FAMILIES: 'THE_FAMILIES',
  THE_BALLAS_GANG: 'THE_BALLAS_GANG',
  LOS_SANTOS_VAGOS: 'LOS_SANTOS_VAGOS',
  MARABUNTA_GRANDE: 'MARABUNTA_GRANDE',
  BLOOD_STREET: 'BLOOD_STREET',
  GOVERNMENT: 'GOVERNMENT',
  POLICE_DEPARTMENT: 'POLICE_DEPARTMENT',
  HOSPITAL: 'HOSPITAL',
  FIB: 'FIB',
  ARMY: 'ARMY',
  SHERIFF: 'SHERIFF',
  LA_COSA_NOSTRA: 'LA_COSA_NOSTRA',
  ALBANIAN_MAFIA: 'ALBANIAN_MAFIA',
  YAKUZA: 'YAKUZA',
  MEXICAN_CARTEL: 'MEXICAN_CARTEL',
  NEWS: 'NEWS',
  THE_LOST: 'THE_LOST',
  MERRYWEATHER_SECURITY: 'MERRYWEATHER_SECURITY'
};

exports.Prisma.ModelName = {
  accounts: 'accounts',
  admins: 'admins',
  advertises: 'advertises',
  alco_clubs: 'alco_clubs',
  banned: 'banned',
  battlepass: 'battlepass',
  business_history: 'business_history',
  businesses: 'businesses',
  character_animation_bind: 'character_animation_bind',
  character_bind_cfg: 'character_bind_cfg',
  characters: 'characters',
  characters_fractions: 'characters_fractions',
  compensation: 'compensation',
  customization: 'customization',
  doors_control: 'doors_control',
  economy_bus_prices: 'economy_bus_prices',
  economy_license_prices: 'economy_license_prices',
  fraction_clothing_sets: 'fraction_clothing_sets',
  job_skills: 'job_skills'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
