// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// import "dotenv/config";


import { defineConfig } from "prisma/config";



export default defineConfig({
  schema: "src/backend/database/prisma/schema.prisma",
  migrations: {
    path: "src/backend/database/prisma/migrations",
  },
  datasource: {
    url: "postgresql://bynarig:bynarig@localhost:5433/redage3?schema=public",
  },
});
