export declare enum BusinessTypeEnum {
	"24_7" = "24_7",
	PETROL_STATION = "PETROL_STATION",
	PREMIUM_AUTOROOM = "PREMIUM_AUTOROOM",
	LUXOR_AUTOROOM = "LUXOR_AUTOROOM",
	LOW_AUTOROOM = "LOW_AUTOROOM",
	MOTOROOM = "MOTOROOM",
	GUN_SHOP = "GUN_SHOP",
	CLOTHES_SHOP = "CLOTHES_SHOP",
	BURGER_SHOT = "BURGER_SHOT",
	TATTOO_SALON = "TATTOO_SALON",
	BARBER_SHOP = "BARBER_SHOP",
	MASKS_SHOP = "MASKS_SHOP",
	LS_CUSTOMS = "LS_CUSTOMS",
	CAR_WASH = "CAR_WASH",
	PET_SHOP = "PET_SHOP",
	ELITE_AUTOROOM = "ELITE_AUTOROOM",
}

export declare const businessType: readonly BusinessTypeEnum[];
